#!/usr/bin/env bash
# Build kanshi profiles from ~/.config/sway/outputs (no "mode preferred" fallback).
set -euo pipefail

outputs="${HOME}/.config/sway/outputs"
kanshi_cfg="${HOME}/.config/kanshi/config"

mkdir -p "${HOME}/.config/kanshi"
tmp="$(mktemp)"

{
  echo "# Generated by sync-kanshi-from-outputs.sh — edit ~/.config/sway/outputs instead."
  echo "# Source: nwg-displays or save-display-layout.sh (Mod+Ctrl+d)."
  echo ""

  if [[ ! -s "${outputs}" ]]; then
    echo "# No saved layout yet."
  else
    echo "profile {"
    awk '
      function emit() {
        if (name == "") return
        line = "  output " name
        if (mode != "") line = line " mode " mode
        if (pos != "") line = line " position " pos
        if (scale != "") line = line " scale " scale
        print line
        name = mode = pos = scale = ""
      }
      /^[[:space:]]*#/ { next }
      /^output / {
        emit()
        rest = substr($0, 8)
        if (rest ~ /\{[[:space:]]*$/) {
          name = $2
          gsub(/"/, "", name)
          inblock = 1
        } else {
          print "  output " rest
        }
        next
      }
      inblock && /^[[:space:]]+mode[[:space:]]+/ {
        mode = $2
        sub(/Hz.*/, "", mode)
        next
      }
      inblock && /^[[:space:]]+position[[:space:]]+/ {
        pos = $2
        if ($3 != "" && $3 != "{") pos = pos "," $3
        gsub(/ /, "", pos)
        next
      }
      inblock && /^[[:space:]]+scale[[:space:]]+/ {
        scale = $2
        next
      }
      inblock && /^[[:space:]]*\}/ {
        emit()
        inblock = 0
        next
      }
      END { emit() }
    ' "${outputs}"
    echo "}"
  fi
} >"${tmp}"

mv -f "${tmp}" "${kanshi_cfg}"
