[loader:image/svg+xml]
Exec=/usr/lib/glycin-loaders/2+/glycin-svg
Sandbox=NotSandboxed
ExposeBaseDir=false
Fontconfig=false

[loader:image/svg+xml-compressed]
Exec=/usr/lib/glycin-loaders/2+/glycin-svg
Sandbox=NotSandboxed
ExposeBaseDir=false
Fontconfig=false
