# SweetPotato overrides for Ly (TUI login)
# Colors are 0xSSRRGGBB — charcoal / potato red / soft fg

allow_empty_password = false
animation = none
asterisk = *
bg = 0x001d1f21
blank_box = true
border_fg = 0x00a73b50
box_title = null
clock = %H:%M
default_input = login
error_bg = 0x001d1f21
error_fg = 0x01a73b50
fg = 0x00f5e6e8
full_color = true
save = true
waylandsessions = /usr/share/wayland-sessions
